# Generated by Django 2.0.4 on 2018-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apodo', models.CharField(max_length=50)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=8)),
                ('digito_verificador', models.PositiveIntegerField(help_text='Si el digito verificador termina en k, reemplace con un 0')),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='digito_verificador',
            field=models.PositiveIntegerField(help_text='Si el digito verificador termina en K, reemplace con un 0'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='peso',
            field=models.PositiveIntegerField(help_text='Indique peso en libras'),
        ),
    ]
